services:
  wanderer-devbox:
    build: 
      dockerfile: ./.devcontainer/wanderer/DockerFile
    container_name: Wanderer-devbox
    stdin_open: true
    tty: true
    volumes:
      - ./Wanderer:/workspace/wanderer
      - ./Readme.md:/workspace/Readme.md
  foundation-devbox:
    build: 
      dockerfile: ./.devcontainer/foundation/DockerFile
    container_name: Foundation-devbox
    stdin_open: true
    tty: true
    volumes:
      - ./foundation:/workspace/foundation
      - ./Readme.md:/workspace/Readme.md
    